name: Format with Spotless

on:
  push:
    branches: [ main, feature/automatic-formatting ]

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Format code with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: spotlessApply --no-daemon

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "style: format code"
          git push
          exit 0